# Generated by Django 2.2 on 2021-10-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorpModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corp_name', models.CharField(max_length=20)),
                ('stock_code', models.CharField(max_length=6)),
                ('corp_code', models.CharField(max_length=8)),
            ],
        ),
    ]
