# Generated by Django 2.2 on 2021-10-23 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chartmodel',
            old_name='name',
            new_name='corp_name',
        ),
        migrations.RenameField(
            model_name='chartmodel',
            old_name='corp_code',
            new_name='stock_code',
        ),
    ]
