# Generated by Django 2.2 on 2021-10-25 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0002_auto_20211023_1050'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChartModel',
        ),
    ]
